# Generated by Django 4.2.4 on 2023-08-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(verbose_name='desc')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('tasks_done', models.BooleanField(default=False)),
            ],
        ),
    ]
